import { FormEvent, useState } from "react";
import { ArrowRight, LockKeyhole } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { api } from "../lib/api";

export default function AdminLogin() {
  const nav=useNavigate(); const [email,setEmail]=useState("admin@hyajaklair.org"); const [password,setPassword]=useState("ChangeMe@2026!"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await api.post("/auth/login",{email,password});nav("/admin")}catch(err){setError(err instanceof Error?err.message:"Login failed")}finally{setBusy(false)}};
  return <div className="min-h-screen bg-[#080808] px-6 py-10 text-white"><div className="mx-auto flex min-h-[calc(100vh-5rem)] max-w-5xl items-center justify-center"><div className="w-full max-w-md rounded-[2rem] border border-white/10 bg-white/[.03] p-8 shadow-2xl backdrop-blur-xl"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-amber-400 text-black"><LockKeyhole/></div><div className="mt-8 text-xs uppercase tracking-[.3em] text-amber-300">HYA Jaklair / Admin</div><h1 className="mt-3 font-display text-4xl font-semibold">Control the story.</h1><p className="mt-3 text-sm leading-6 text-white/40">Manage media, events, activities, team, announcements and site settings.</p><form onSubmit={submit} className="mt-8 space-y-4"><Field label="Email" type="email" value={email} onChange={setEmail}/><Field label="Password" type="password" value={password} onChange={setPassword}/>{error&&<div className="rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{error}</div>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 font-semibold text-black">{busy?"Signing in…":"Sign in"}<ArrowRight size={16}/></button></form><div className="mt-5 rounded-xl border border-white/8 bg-white/[.02] p-4 text-xs leading-5 text-white/40">Need another administrator? A signed-in admin can create accounts from <span className="text-amber-300">Admin Accounts</span> in the dashboard.</div></div></div></div>
}
function Field({label,type,value,onChange}:{label:string;type:string;value:string;onChange:(v:string)=>void}){return <label className="block text-xs uppercase tracking-[.16em] text-white/35">{label}<input required type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-4 text-white outline-none focus:border-amber-400/50"/></label>}
